import { Injectable } from '@nestjs/common';
// import { InjectRepository } from '@nestjs/typeorm';
// import { HomePageEntry } from '../entity/homepage.entity';
// import { getConnection, Repository } from 'typeorm';
@Injectable()
export class HomePageService {
    // constructor(
    //     @InjectRepository(HomePageEntry)
    //     private readonly HomeRepository: Repository<HomePageEntry>,
    // ) { }
    getAll(): object {
        return {
            result: [
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 116,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 118,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 153,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 154,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 155,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 156,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '特朗普',
                    is_attention: false,
                    A01001: '头像',
                    _id: 180,
                    A01ADD06: 1,
                },
                {
                    A01018: '总统',
                    A01002: '特朗普',
                    is_attention: false,
                    A01001: '头像',
                    _id: 183,
                    A01ADD06: 1,
                },
                {
                    A01018: '反对派',
                    A01002: '黄之锋',
                    is_attention: false,
                    A01001: '头像',
                    _id: 185,
                    A01ADD06: 1,
                },
                {
                    A01018: '反对派',
                    A01002: '黄之锋',
                    is_attention: false,
                    A01001: '头像',
                    _id: 186,
                    A01ADD06: 1,
                },
                {
                    A01018: '反对派',
                    A01002: '黄之锋',
                    is_attention: false,
                    A01001: '头像',
                    _id: 187,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '特朗普',
                    is_attention: false,
                    A01001: '头像',
                    _id: 209,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '特朗普',
                    is_attention: false,
                    A01001: '头像',
                    _id: 210,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '特朗普',
                    is_attention: false,
                    A01001: '头像',
                    _id: 211,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '特朗普',
                    is_attention: false,
                    A01001: '头像',
                    _id: 212,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 300,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 301,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 302,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 303,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 304,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 305,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 306,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 307,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 308,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 309,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 310,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 311,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 312,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 313,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 314,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 315,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 316,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 317,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 318,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 319,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 320,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 321,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 322,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 323,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 324,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 325,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 326,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 327,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 328,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 329,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 330,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 331,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 332,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 333,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 334,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 335,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 336,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 337,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 338,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 339,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 340,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 341,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 342,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 343,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 344,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 345,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 346,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 347,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 348,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 349,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 350,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 351,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 352,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 353,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 354,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 355,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 356,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 357,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 358,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 359,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 360,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 361,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 362,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 363,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 364,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 365,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 366,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 367,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 368,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 369,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 370,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 371,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 372,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 373,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 374,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 375,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 376,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 377,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 378,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 379,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 380,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 381,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 382,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 383,
                    A01ADD06: 1,
                },
                {
                    A01018: '政客',
                    A01002: '希拉里',
                    is_attention: false,
                    A01001: '头像',
                    _id: 384,
                    A01ADD06: 1,
                },
            ],
            downloadable: {
                A10: false,
                A11: false,
                A01: true,
                A12: false,
                A02: false,
                A13: false,
                A03: false,
                A14: false,
                A04: false,
                A15: false,
                A05: false,
                A16: false,
                A06: false,
                A07: false,
                A08: false,
                A09: false,
            },
            attention_count: 0,
            count: 9715,
            distinct_occupations: [
                '',
                '反对派',
                '总统',
                '待业',
                '政客',
                '企业家',
            ],
            status: 1,
        };
    }
    getDetail(): object {
        return {
            result: {
                A10: [
                    {
                        A10004: '民主党',
                        A10005: '无备注',
                        A10000: 180,
                        A10001: 132,
                        A10002: '1966年4月1日',
                        A10003: '1966年4月1日',
                        A10ADD00: {},
                    },
                ],
                A11: [
                    {
                        A11005: '无备注',
                        A11001: 137,
                        A11002: '1966年4月1日',
                        A11003: '1966年4月1日',
                        A11004: '民主党',
                        A11000: 180,
                        A11ADD00: {},
                    },
                ],
                A12: [
                    {
                        A12002: '1966年4月1日',
                        A12003: '1966年4月1日',
                        A12004: '民主人士',
                        A12005: '无备注',
                        A12000: 180,
                        A12001: 137,
                        A12ADD00: {},
                    },
                ],
                A01: {
                    A01000: 180,
                    A01022: [
                        {
                            账号: '.com',
                            类型: '推特',
                        },
                    ],
                    A01001: '头像',
                    A01023: '无',
                    A01020: '12345678',
                    A01021: '香港',
                    A01008: '纽约',
                    A01009: [
                        {
                            国籍: '美国',
                            加入时间: '2000年1月1日',
                            退出时间: '2000年1月1日',
                        },
                    ],
                    A01006: '男',
                    A01007: '1947年10月26日',
                    A01004: '特朗普',
                    A01026: '文本录入',
                    A01005: 'Hilary',
                    A01002: '特朗普',
                    A01024: '纽约',
                    A01003: '特朗普',
                    A01025: '无',
                    A01ADD00: {},
                    A01011: '博士',
                    A01012: '耶鲁法学博士',
                    A01010: '美国纽约州',
                    A01019: '民主党议员',
                    A01017: '民主党',
                    A01018: '政客',
                    A01015: '民主党',
                    A01016: '民主党',
                    A01013: '法学',
                    A01014: '自由主义',
                },
                A13: [
                    {
                        A13004: '美国荣誉勋章',
                        A13003: '1966年4月1日',
                        A13ADD00: {},
                        A13000: 180,
                        A13002: '1966年4月1日',
                        A13001: 132,
                    },
                ],
                A02: [
                    {
                        A02007: '无',
                        A02ADD00: {},
                        A02005: '天主教',
                        A02006: '无',
                        A02003: '无',
                        A02004: '基督教',
                        A02001: 177,
                        A02002: '1947年10月26日',
                        A02000: 180,
                    },
                ],
                A03: [
                    {
                        A03009: [
                            {
                                国籍: '美国',
                                加入时间: '2020年1月1日',
                                退出时间: '2020年1月1日',
                            },
                        ],
                        A03008: [
                            {
                                毕业情况: '毕业',
                                结束日期: '2020年1月1日',
                                机构名称: '耶鲁',
                                开始日期: '2020年1月1日',
                                备注: '无',
                            },
                        ],
                        A03007: '美国政府',
                        A03006: '美国前总统',
                        A03005: '无',
                        A03004: '1946年8月19日',
                        A03003: '克林顿',
                        A03002: '丈夫',
                        A03001: 259,
                        A03000: 180,
                        A03010: '无',
                        A03ADD00: {},
                    },
                ],
                A14: [
                    {
                        A14ADD00: {},
                        A14004: '1966年4月1日',
                        A14001: 132,
                        A14000: 180,
                        A14003: '竞选美国总统',
                        A14002: '竞选美国总统',
                    },
                ],
                A15: [
                    {
                        A15007: [
                            {
                                1: 2,
                            },
                        ],
                        A15008: '123',
                        A15005: '美国复兴',
                        A15006: [
                            {
                                姓名: '姓名',
                            },
                        ],
                        A15003: '竞选美国总统',
                        A15004: 1,
                        A15001: 132,
                        A15002: '1966年4月1日',
                        A15000: 180,
                        A15ADD00: {},
                    },
                ],
                A04: [
                    {
                        A04006: '无备注',
                        A04005: '博士',
                        A04004: '耶鲁',
                        A04003: '1952年4月1日',
                        A04002: '1948年4月1日',
                        A04ADD00: {},
                        A04001: 132,
                        A04000: 180,
                    },
                ],
                A05: [
                    {
                        A05000: 180,
                        A05001: 132,
                        A05002: '1948年4月1日',
                        A05003: '1952年4月1日',
                        A05004: '政客',
                        A05ADD00: {},
                        A05005: '美国政府',
                        A05006: '无备注',
                    },
                ],
                A16: [
                    {
                        A16004: '华盛顿时报',
                        A16005: '123',
                        A16002: '《美国复兴》',
                        A16003: '1966年4月1日',
                        A16ADD00: {},
                        A16000: 180,
                        A16001: 138,
                    },
                ],
                A06: [
                    {
                        A06000: 180,
                        A06001: 132,
                        A06002: '议员',
                        A06003: '1966年',
                        A06004: '无备注',
                        A06ADD00: {},
                    },
                ],
                A07: [
                    {
                        A07001: 132,
                        A07000: 180,
                        A07003: '议员培训',
                        A07002: '1966年4月1日',
                        A07005: '支持美国政府',
                        A07004: '纽约',
                        A07007: '无备注',
                        A07006: '优秀',
                        A07ADD00: {},
                    },
                ],
                A08: [
                    {
                        A08002: '1966年4月1日',
                        A08001: 137,
                        A08ADD00: {},
                        A08004: '自由主义修改',
                        A08003: '1966年4月1日',
                        A08005: '无备注',
                        A08000: 180,
                    },
                ],
                A09: [
                    {
                        A09004: '民主党新增',
                        A09005: '无备注',
                        A09002: '1966年4月1日',
                        A09003: '1966年4月1日',
                        A09ADD00: {},
                        A09000: 180,
                        A09001: 154,
                    },
                ],
            },
            is_attention: false,
            A01ADD06: 1,
            status: 1,
        }
    }

    getPriviledges(): object {
        return {
            priviledges_and_values: {
                A10: [
                    {
                        A10004: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A10005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A10000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A10001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A10002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A10003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A10ADD00: {},
                    },
                ],
                A11: [
                    {
                        A11005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A11001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A11002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A11003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A11004: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A11000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A11ADD00: {},
                    },
                ],
                A01: {
                    A01000: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: 191,
                        type: 'int',
                    },
                    A01022: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: [
                            {
                                账号: '.com',
                                类型: '推特',
                            },
                        ],
                        type: 'json',
                    },
                    A01001: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '头像',
                        type: 'varchar',
                    },
                    A01023: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '无',
                        type: 'varchar',
                    },
                    A01020: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '12345678',
                        type: 'varchar',
                    },
                    A01021: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '澳门',
                        type: 'varchar',
                    },
                    A01008: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '纽约',
                        type: 'varchar',
                    },
                    A01009: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: [
                            {
                                国籍: '美国',
                                加入时间: '2000年1月1日',
                                退出时间: '2000年1月1日',
                            },
                        ],
                        type: 'json',
                    },
                    A01006: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '男',
                        type: 'varchar',
                    },
                    A01007: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '1947年10月26日',
                        type: 'varchar',
                    },
                    A01004: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '何猷君222',
                        type: 'varchar',
                    },
                    A01026: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '文本录入',
                        type: 'text',
                    },
                    A01005: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: 'Hilary',
                        type: 'varchar',
                    },
                    A01002: {
                        addable: true,
                        editable: true,
                        is_must: 2,
                        old_value: '何猷君222',
                        type: 'varchar',
                    },
                    A01024: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '纽约',
                        type: 'varchar',
                    },
                    A01003: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '何猷君222',
                        type: 'varchar',
                    },
                    A01025: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '无',
                        type: 'varchar',
                    },
                    A01ADD00: {},
                    A01011: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '博士',
                        type: 'varchar',
                    },
                    A01012: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '耶鲁法学博士',
                        type: 'varchar',
                    },
                    A01010: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '美国纽约州',
                        type: 'varchar',
                    },
                    A01019: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '民主党议员',
                        type: 'varchar',
                    },
                    A01017: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '民主党',
                        type: 'varchar',
                    },
                    A01018: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '待业',
                        type: 'varchar',
                    },
                    A01015: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '民主党',
                        type: 'varchar',
                    },
                    A01016: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '民主党',
                        type: 'varchar',
                    },
                    A01013: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '法学',
                        type: 'varchar',
                    },
                    A01014: {
                        addable: true,
                        editable: true,
                        is_must: 1,
                        old_value: '自由主义',
                        type: 'varchar',
                    },
                },
                A12: [
                    {
                        A12002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A12003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A12004: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A12005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A12000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A12001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A12ADD00: {},
                    },
                ],
                A02: [
                    {
                        A02007: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            old_value: '无',
                            type: 'text',
                        },
                        A02ADD00: {},
                        A02005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            old_value: '佛教',
                            type: 'varchar',
                        },
                        A02006: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            old_value: '无',
                            type: 'varchar',
                        },
                        A02003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            old_value: '无',
                            type: 'varchar',
                        },
                        A02004: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            old_value: '佛教',
                            type: 'varchar',
                        },
                        A02001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            old_value: 190,
                            type: 'int',
                        },
                        A02002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            old_value: '1947年10月26日',
                            type: 'varchar',
                        },
                        A02000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            old_value: 191,
                            type: 'int',
                        },
                    },
                ],
                A13: [
                    {
                        A13000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A13002: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A13001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A13004: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A13003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A13ADD00: {},
                    },
                ],
                A03: [
                    {
                        A03009: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'json',
                        },
                        A03008: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'json',
                        },
                        A03007: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A03006: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A03005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A03004: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A03003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A03002: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A03001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A03000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A03010: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A03ADD00: {},
                    },
                ],
                A14: [
                    {
                        A14001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A14ADD00: {},
                        A14000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A14003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A14002: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'text',
                        },
                        A14004: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                    },
                ],
                A15: [
                    {
                        A15007: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'json',
                        },
                        A15008: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A15005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A15006: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'json',
                        },
                        A15003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A15004: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A15001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A15002: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A15000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A15ADD00: {},
                    },
                ],
                A04: [
                    {
                        A04006: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A04005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A04004: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A04003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A04002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A04001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A04ADD00: {},
                        A04000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                    },
                ],
                A16: [
                    {
                        A16004: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A16005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A16002: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'text',
                        },
                        A16003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A16000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A16ADD00: {},
                        A16001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                    },
                ],
                A05: [
                    {
                        A05000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A05001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A05002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A05003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A05004: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A05005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A05ADD00: {},
                        A05006: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                    },
                ],
                A06: [
                    {
                        A06000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A06001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A06002: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A06ADD00: {},
                        A06003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A06004: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                    },
                ],
                A07: [
                    {
                        A07001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A07000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A07003: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A07002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A07005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A07004: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A07007: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A07006: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A07ADD00: {},
                    },
                ],
                A08: [
                    {
                        A08002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A08001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A08004: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A08ADD00: {},
                        A08003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A08005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A08000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                    },
                ],
                A09: [
                    {
                        A09004: {
                            addable: true,
                            editable: true,
                            is_must: 2,
                            type: 'varchar',
                        },
                        A09005: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'text',
                        },
                        A09002: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A09003: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'varchar',
                        },
                        A09ADD00: {},
                        A09000: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                        A09001: {
                            addable: true,
                            editable: true,
                            is_must: 1,
                            type: 'int',
                        },
                    },
                ],
            },
            status: 1,
        };
    }
}
